-- Add tech-focused posts with proper tags and cover images
-- Topics: AI, Technology, Cybersecurity, Programming, Startups, Productivity, Design, Data Science, Machine Learning, Web Development

INSERT INTO posts (id, author_id, slug, title, content, excerpt, tags, reading_time_minutes, word_count, status, published_at, view_count, like_count, comment_count, is_premium, cover_image_url, created_at, updated_at) VALUES

-- AI posts (5)
('20000000-0000-0000-0000-000000000001', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'the-future-of-generative-ai', 'The Future of Generative AI',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Generative AI is transforming how we create content, from text and images to code and music. Large language models can now write essays, generate art, and even compose music. This shift is changing creative industries and raising questions about originality, copyright, and the role of human creativity.","type":"text"}]},{"type":"paragraph","content":[{"text":"The technology is advancing rapidly. Models are becoming more capable, more efficient, and more accessible. Soon, generative AI will be integrated into every creative tool, making it easier for anyone to produce high-quality content. The challenge will be ensuring these tools are used responsibly and ethically.","type":"text"}]},{"type":"paragraph","content":[{"text":"As generative AI becomes more powerful, the line between human and machine creativity will blur. The future belongs to those who can harness these tools while maintaining their unique voice and perspective.","type":"text"}]}]}',
 'How generative AI is transforming content creation and creative industries.',
 '["AI"]', 5, 1000, 'published', NOW() - interval '1 day', 280, 45, 6, false, 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000002', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'ai-ethics-and-responsible-ai', 'AI Ethics and Responsible AI',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"As AI systems become more powerful, questions about ethics, bias, and responsibility become more urgent. AI can perpetuate biases, make unfair decisions, and be used for harmful purposes. Ensuring AI is developed and used responsibly is one of the most important challenges of our time.","type":"text"}]},{"type":"paragraph","content":[{"text":"Responsible AI requires transparency, accountability, and fairness. We need to understand how AI systems make decisions, ensure they don''t discriminate, and hold developers accountable for their creations. This requires collaboration between technologists, ethicists, policymakers, and the public.","type":"text"}]},{"type":"paragraph","content":[{"text":"The future of AI depends on how we address these ethical challenges. By prioritizing responsible AI development, we can harness the benefits of AI while minimizing its risks.","type":"text"}]}]}',
 'The importance of ethics and responsibility in AI development.',
 '["AI"]', 5, 1050, 'published', NOW() - interval '2 days', 310, 52, 8, false, 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000003', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'machine-learning-for-beginners', 'Machine Learning for Beginners',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Machine learning is a subset of AI that enables computers to learn from data without being explicitly programmed. Instead of following rigid rules, machine learning models identify patterns and make predictions based on examples. This makes them incredibly powerful for tasks like image recognition, natural language processing, and recommendation systems.","type":"text"}]},{"type":"paragraph","content":[{"text":"Getting started with machine learning is easier than ever. Libraries like TensorFlow, PyTorch, and scikit-learn provide tools for building and training models. Online courses and tutorials make it accessible to anyone with basic programming skills. The key is understanding the fundamentals: data, models, training, and evaluation.","type":"text"}]},{"type":"paragraph","content":[{"text":"Machine learning is transforming industries from healthcare to finance to entertainment. Whether you''re a developer, data scientist, or just curious, learning machine learning opens up new possibilities for solving complex problems.","type":"text"}]}]}',
 'A beginner''s guide to machine learning and how to get started.',
 '["Machine Learning"]', 5, 1100, 'published', NOW() - interval '3 days', 340, 58, 7, false, 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000004', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'deep-learning-neural-networks', 'Deep Learning and Neural Networks',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Deep learning is a subset of machine learning that uses neural networks with many layers to learn complex patterns. Inspired by the human brain, these networks can recognize images, understand speech, and even generate human-like text. Deep learning is behind many of the recent breakthroughs in AI.","type":"text"}]},{"type":"paragraph","content":[{"text":"Neural networks consist of layers of interconnected nodes that process information. Each layer learns to recognize increasingly complex features, from simple edges in images to abstract concepts. This hierarchical learning is what makes deep learning so powerful for tasks like computer vision and natural language processing.","type":"text"}]},{"type":"paragraph","content":[{"text":"Deep learning requires large amounts of data and computational power. But as hardware improves and datasets grow, deep learning is becoming more accessible and more capable. The future of AI is deeply intertwined with the continued advancement of neural networks.","type":"text"}]}]}',
 'Understanding deep learning and neural networks.',
 '["Machine Learning"]', 5, 1020, 'published', NOW() - interval '4 days', 290, 48, 5, false, 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000005', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'natural-language-processing', 'Natural Language Processing Explained',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Natural Language Processing (NLP) is a branch of AI that enables computers to understand, interpret, and generate human language. From chatbots to translation services to sentiment analysis, NLP is transforming how we interact with machines. The technology has advanced rapidly in recent years, making it possible for computers to understand context, nuance, and even emotion in text.","type":"text"}]},{"type":"paragraph","content":[{"text":"Modern NLP uses deep learning models like transformers to process and generate language. These models can answer questions, summarize documents, translate languages, and even write creative content. The key innovation is the ability to understand context and generate human-like responses.","type":"text"}]},{"type":"paragraph","content":[{"text":"NLP is everywhere: virtual assistants, search engines, social media, customer service. As the technology improves, NLP will become even more integrated into our daily lives, making human-computer interaction more natural and intuitive.","type":"text"}]}]}',
 'How Natural Language Processing works and its applications.',
 '["AI"]', 5, 1080, 'published', NOW() - interval '5 days', 260, 42, 4, false, 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80', NOW(), NOW()),

-- Technology posts (5)
('20000000-0000-0000-0000-000000000006', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'the-future-of-web-development', 'The Future of Web Development',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Web development is evolving rapidly. New frameworks, tools, and paradigms are changing how we build websites and applications. From server-side rendering to edge computing to AI-assisted development, the future of web development is faster, more efficient, and more accessible than ever.","type":"text"}]},{"type":"paragraph","content":[{"text":"Modern web development emphasizes performance, accessibility, and user experience. Frameworks like React, Vue, and Svelte make it easier to build complex applications. Tools like Next.js and Remix enable server-side rendering for better SEO and faster load times. The focus is on creating fast, responsive, and accessible web experiences.","type":"text"}]},{"type":"paragraph","content":[{"text":"The future of web development is about building better experiences for users and developers alike. As tools improve and best practices evolve, web development will continue to be a dynamic and exciting field.","type":"text"}]}]}',
 'How web development is evolving and what''s next.',
 '["Web Development"]', 5, 950, 'published', NOW() - interval '1 day', 240, 38, 5, false, 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000007', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'cloud-computing-fundamentals', 'Cloud Computing Fundamentals',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Cloud computing has transformed how we build and deploy applications. Instead of managing physical servers, we can rent computing resources from providers like AWS, Azure, and Google Cloud. This shift has made it easier to scale applications, reduce costs, and focus on building features rather than managing infrastructure.","type":"text"}]},{"type":"paragraph","content":[{"text":"Cloud computing offers many benefits: scalability, reliability, cost-effectiveness, and global reach. You can deploy applications in minutes, scale them to handle millions of users, and pay only for what you use. The cloud also enables new architectures like serverless, containers, and microservices.","type":"text"}]},{"type":"paragraph","content":[{"text":"Understanding cloud computing is essential for modern developers. Whether you''re building a small app or a large enterprise system, the cloud provides the tools and infrastructure to build, deploy, and scale your applications efficiently.","type":"text"}]}]}',
 'An introduction to cloud computing and its benefits.',
 '["Technology"]', 5, 920, 'published', NOW() - interval '2 days', 220, 35, 4, false, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000008', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'cybersecurity-best-practices', 'Cybersecurity Best Practices for 2026',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Cybersecurity is more important than ever. As our lives become increasingly digital, protecting our data and systems from threats is critical. From ransomware to phishing to data breaches, the threats are real and growing. But with the right practices, we can significantly reduce our risk.","type":"text"}]},{"type":"paragraph","content":[{"text":"Best practices include using strong, unique passwords, enabling two-factor authentication, keeping software updated, being cautious with emails and links, and regularly backing up data. For organizations, implementing zero-trust security, conducting regular security audits, and training employees on security awareness are essential.","type":"text"}]},{"type":"paragraph","content":[{"text":"Cybersecurity is everyone''s responsibility. By following best practices and staying informed about the latest threats, we can protect ourselves and our organizations from cyber attacks.","type":"text"}]}]}',
 'Essential cybersecurity practices to protect your data and systems.',
 '["Cybersecurity"]', 5, 980, 'published', NOW() - interval '3 days', 270, 41, 6, false, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000009', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'the-rise-of-quantum-computing', 'The Rise of Quantum Computing',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Quantum computing is a revolutionary approach to computation that leverages the principles of quantum mechanics. Unlike classical computers that use bits (0 or 1), quantum computers use qubits that can exist in multiple states simultaneously. This allows them to solve certain problems exponentially faster than classical computers.","type":"text"}]},{"type":"paragraph","content":[{"text":"Quantum computing has the potential to revolutionize fields like cryptography, drug discovery, optimization, and AI. It could break current encryption methods, simulate complex molecules for drug development, and solve optimization problems that are intractable for classical computers.","type":"text"}]},{"type":"paragraph","content":[{"text":"While quantum computing is still in its early stages, rapid progress is being made. Major tech companies and research institutions are investing heavily in quantum research. The future of computing may well be quantum.","type":"text"}]}]}',
 'How quantum computing works and its potential impact.',
 '["Technology"]', 5, 960, 'published', NOW() - interval '4 days', 250, 39, 5, false, 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000010', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'the-internet-of-things', 'The Internet of Things: Connecting Everything',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"The Internet of Things (IoT) is a network of connected devices that collect and share data. From smart homes to industrial sensors to wearable devices, IoT is transforming how we interact with the physical world. These devices can monitor, control, and optimize everything from home appliances to factory equipment.","type":"text"}]},{"type":"paragraph","content":[{"text":"IoT devices use sensors, connectivity, and data processing to gather information and make decisions. They can automate tasks, improve efficiency, and provide valuable insights. For example, smart thermostats learn your preferences and save energy, while industrial sensors predict equipment failures before they happen.","type":"text"}]},{"type":"paragraph","content":[{"text":"As IoT technology advances, we''ll see more connected devices and smarter systems. The challenge will be managing the complexity, security, and privacy of billions of connected devices.","type":"text"}]}]}',
 'How the Internet of Things is connecting and transforming our world.',
 '["Technology"]', 5, 940, 'published', NOW() - interval '5 days', 230, 36, 4, false, 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80', NOW(), NOW()),

-- Programming posts (5)
('20000000-0000-0000-0000-000000000011', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'clean-code-principles', 'Clean Code Principles Every Developer Should Know',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Clean code is code that is easy to read, understand, and maintain. It follows principles like meaningful naming, small functions, single responsibility, and avoiding duplication. Writing clean code makes your codebase more maintainable and your team more productive.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key principles include: use meaningful names, keep functions small and focused, follow the single responsibility principle, avoid magic numbers, write self-documenting code, and refactor regularly. These practices make your code easier to understand, test, and modify.","type":"text"}]},{"type":"paragraph","content":[{"text":"Clean code is not just about aesthetics—it''s about sustainability. Code that is clean and well-organized is easier to debug, extend, and collaborate on. Investing time in writing clean code pays off in the long run.","type":"text"}]}]}',
 'Essential principles for writing clean, maintainable code.',
 '["Programming"]', 5, 900, 'published', NOW() - interval '1 day', 210, 33, 5, false, 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000012', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'design-patterns-explained', 'Design Patterns Explained',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Design patterns are proven solutions to common programming problems. They provide a shared vocabulary and best practices for solving recurring challenges in software design. Understanding design patterns makes you a better developer and helps you write more maintainable code.","type":"text"}]},{"type":"paragraph","content":[{"text":"Common patterns include: Singleton (ensuring a class has only one instance), Factory (creating objects without specifying their exact class), Observer (notifying objects of state changes), and Strategy (defining a family of algorithms). Each pattern solves a specific type of problem and provides a template for solving it.","type":"text"}]},{"type":"paragraph","content":[{"text":"Design patterns are not a silver bullet, but they are powerful tools when used appropriately. They help you write code that is more flexible, reusable, and easier to understand. Learning design patterns is an essential part of becoming a skilled developer.","type":"text"}]}]}',
 'Understanding common design patterns and when to use them.',
 '["Programming"]', 5, 880, 'published', NOW() - interval '2 days', 200, 31, 4, false, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000013', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'test-driven-development', 'Test-Driven Development: Why It Matters',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Test-Driven Development (TDD) is a software development approach where you write tests before writing code. This might seem counterintuitive, but it has many benefits: better code quality, fewer bugs, faster development, and more confidence in your code. TDD forces you to think about requirements and design before implementation.","type":"text"}]},{"type":"paragraph","content":[{"text":"The TDD cycle is simple: write a failing test, write the minimum code to make it pass, then refactor. This cycle ensures that your code is always tested and that you only write the code you need. TDD also serves as documentation, showing how your code is supposed to work.","type":"text"}]},{"type":"paragraph","content":[{"text":"While TDD requires discipline and practice, the benefits are worth it. Teams that practice TDD report fewer bugs, faster development, and higher code quality. If you''re not already using TDD, it''s worth trying.","type":"text"}]}]}',
 'The benefits and practice of Test-Driven Development.',
 '["Programming"]', 5, 860, 'published', NOW() - interval '3 days', 190, 29, 3, false, 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000014', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'version-control-best-practices', 'Version Control Best Practices with Git',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Version control is essential for modern software development. Git is the most popular version control system, and for good reason: it''s fast, distributed, and powerful. But using Git effectively requires more than just knowing the basic commands—it requires understanding best practices for collaboration, branching, and code management.","type":"text"}]},{"type":"paragraph","content":[{"text":"Best practices include: commit early and often, write meaningful commit messages, use branches for features and fixes, keep the main branch stable, review code before merging, and use pull requests for collaboration. These practices make your codebase more stable and your team more productive.","type":"text"}]},{"type":"paragraph","content":[{"text":"Git is a powerful tool, but it''s only as good as how you use it. By following best practices, you can make version control work for you and your team, not against you.","type":"text"}]}]}',
 'Best practices for using Git and version control effectively.',
 '["Programming"]', 5, 840, 'published', NOW() - interval '4 days', 180, 27, 4, false, 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000015', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'api-design-principles', 'API Design Principles for Modern Applications',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"APIs are the backbone of modern applications. They enable communication between different services, systems, and applications. Good API design is essential for building scalable, maintainable, and user-friendly applications. Poor API design leads to confusion, bugs, and technical debt.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key principles include: use RESTful conventions, version your APIs, provide clear documentation, use meaningful error messages, implement proper authentication and authorization, and design for backward compatibility. These practices make your APIs easier to use, maintain, and evolve.","type":"text"}]},{"type":"paragraph","content":[{"text":"A well-designed API is intuitive, consistent, and well-documented. It makes developers'' lives easier and enables faster, more reliable integration. Investing time in good API design pays off in the long run.","type":"text"}]}]}',
 'Principles for designing good APIs for modern applications.',
 '["Programming"]', 5, 820, 'published', NOW() - interval '5 days', 170, 25, 3, false, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80', NOW(), NOW()),

-- Startups posts (3)
('20000000-0000-0000-0000-000000000016', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'building-a-startup-from-scratch', 'Building a Startup from Scratch',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Building a startup is one of the most challenging and rewarding things you can do. It requires vision, persistence, and a willingness to learn from failure. From idea to launch to growth, the startup journey is full of ups and downs. But with the right approach, you can increase your chances of success.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key steps include: validate your idea, build a minimum viable product (MVP), find product-market fit, and scale. Each step requires different skills and strategies. The most important thing is to focus on solving a real problem for real people.","type":"text"}]},{"type":"paragraph","content":[{"text":"Building a startup is not easy, but it''s one of the most impactful things you can do. Whether you succeed or fail, you''ll learn valuable lessons that will serve you throughout your career.","type":"text"}]}]}',
 'A guide to building a startup from idea to launch.',
 '["Startups"]', 5, 780, 'published', NOW() - interval '1 day', 160, 24, 3, false, 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000017', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'startup-funding-explained', 'Startup Funding Explained',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Funding is one of the most important aspects of building a startup. From bootstrapping to angel investors to venture capital, there are many ways to fund your startup. Each option has its own advantages, disadvantages, and requirements. Understanding the funding landscape is essential for any entrepreneur.","type":"text"}]},{"type":"paragraph","content":[{"text":"Bootstrapping means funding your startup with your own money. It gives you full control but limits your resources. Angel investors provide early-stage funding in exchange for equity. Venture capital provides larger amounts of funding for high-growth startups. Each stage of funding has different expectations and requirements.","type":"text"}]},{"type":"paragraph","content":[{"text":"The right funding strategy depends on your startup''s stage, goals, and growth potential. Understanding your options and choosing the right path can make the difference between success and failure.","type":"text"}]}]}',
 'Understanding different types of startup funding and how to choose the right one.',
 '["Startups"]', 5, 760, 'published', NOW() - interval '2 days', 150, 22, 2, false, 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000018', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'product-market-fit', 'Finding Product-Market Fit',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Product-market fit is when your product satisfies a strong market demand. It''s the holy grail of startups—the point where customers love your product and tell others about it. Finding product-market fit is essential for startup success, but it''s not easy to achieve.","type":"text"}]},{"type":"paragraph","content":[{"text":"Signs of product-market fit include: rapid growth, high retention, word-of-mouth referrals, and customers who are disappointed when they can''t use your product. Achieving it requires iterating on your product based on customer feedback, focusing on solving a real problem, and being willing to pivot if necessary.","type":"text"}]},{"type":"paragraph","content":[{"text":"Product-market fit is not a destination but a journey. Even after achieving it, you need to continue iterating and improving to maintain it. The most successful startups are those that never stop listening to their customers.","type":"text"}]}]}',
 'How to find and maintain product-market fit for your startup.',
 '["Startups"]', 5, 740, 'published', NOW() - interval '3 days', 140, 20, 2, false, 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80', NOW(), NOW()),

-- Productivity posts (3)
('20000000-0000-0000-0000-000000000019', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'deep-work-guide', 'Deep Work: A Guide to Focused Productivity',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Deep work is the ability to focus without distraction on a cognitively demanding task. In a world of constant interruptions and distractions, deep work is becoming increasingly rare and valuable. The ability to focus deeply is a superpower that can dramatically increase your productivity and the quality of your work.","type":"text"}]},{"type":"paragraph","content":[{"text":"To achieve deep work, you need to: eliminate distractions, schedule dedicated focus time, create rituals and routines, and embrace boredom. Deep work requires discipline and practice, but the rewards are worth it. You''ll produce higher quality work in less time.","type":"text"}]},{"type":"paragraph","content":[{"text":"Deep work is not just about productivity—it''s about fulfillment. When you''re deeply focused on meaningful work, you experience flow and satisfaction. In a distracted world, the ability to focus deeply is more valuable than ever.","type":"text"}]}]}',
 'How to achieve deep work and focused productivity in a distracted world.',
 '["Productivity"]', 5, 720, 'published', NOW() - interval '1 day', 130, 19, 2, false, 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000020', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'time-management-strategies', 'Time Management Strategies for Developers',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Time management is one of the most important skills for developers. Between coding, meetings, emails, and other responsibilities, it''s easy to feel overwhelmed. Effective time management can help you be more productive, less stressed, and more successful in your work.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key strategies include: prioritize ruthlessly, use time blocking, eliminate time wasters, batch similar tasks, and take regular breaks. The goal is to focus on high-impact activities and eliminate low-value tasks. Time management is not about doing more—it''s about doing what matters most.","type":"text"}]},{"type":"paragraph","content":[{"text":"Good time management is not about working longer hours—it''s about working smarter. By managing your time effectively, you can achieve more in less time and have more energy for the things that matter.","type":"text"}]}]}',
 'Effective time management strategies for developers and knowledge workers.',
 '["Productivity"]', 5, 700, 'published', NOW() - interval '2 days', 120, 17, 2, false, 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000021', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'remote-work-best-practices', 'Remote Work Best Practices',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Remote work has become the norm for many developers and knowledge workers. While it offers flexibility and freedom, it also presents unique challenges: isolation, distractions, communication difficulties, and work-life balance. Following best practices can help you thrive in a remote work environment.","type":"text"}]},{"type":"paragraph","content":[{"text":"Best practices include: create a dedicated workspace, establish a routine, overcommunicate with your team, take regular breaks, and set boundaries between work and personal life. The key is to be intentional about how you work and communicate.","type":"text"}]},{"type":"paragraph","content":[{"text":"Remote work can be incredibly rewarding, but it requires discipline and self-awareness. By following best practices, you can be productive, connected, and fulfilled in your remote work.","type":"text"}]}]}',
 'Best practices for thriving in a remote work environment.',
 '["Productivity"]', 5, 680, 'published', NOW() - interval '3 days', 110, 15, 2, false, 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80', NOW(), NOW()),

-- Design posts (3)
('20000000-0000-0000-0000-000000000022', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'ui-ux-design-principles', 'UI/UX Design Principles for Better Products',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"UI/UX design is about creating products that are both beautiful and functional. Good design makes products intuitive, accessible, and delightful to use. Poor design leads to confusion, frustration, and abandonment. Understanding design principles is essential for building products that users love.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key principles include: clarity (make it obvious what to do), consistency (use familiar patterns), feedback (show users what''s happening), and accessibility (design for everyone). Good design is invisible—it just works.","type":"text"}]},{"type":"paragraph","content":[{"text":"Great UI/UX design is not about making things pretty—it''s about making things work well. When design is done well, users don''t notice it. When it''s done poorly, users notice everything.","type":"text"}]}]}',
 'Essential UI/UX design principles for building better products.',
 '["Design"]', 5, 660, 'published', NOW() - interval '1 day', 100, 14, 2, false, 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000023', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'design-systems-guide', 'Design Systems: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"A design system is a collection of reusable components, patterns, and guidelines that help teams build consistent products. Design systems provide a shared language and toolkit for designers and developers, making it easier to build high-quality products quickly and consistently.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key components include: design tokens (colors, typography, spacing), component libraries (buttons, forms, cards), patterns (navigation, layouts, interactions), and guidelines (accessibility, usage, best practices). A good design system is comprehensive, well-documented, and easy to use.","type":"text"}]},{"type":"paragraph","content":[{"text":"Design systems are essential for scaling design and development. They ensure consistency, reduce duplication, and enable faster, higher-quality product development. Investing in a design system pays off in the long run.","type":"text"}]}]}',
 'How to build and use design systems for consistent product development.',
 '["Design"]', 5, 640, 'published', NOW() - interval '2 days', 90, 12, 2, false, 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000024', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'accessibility-in-design', 'Accessibility in Design: Why It Matters',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Accessibility is about designing products that everyone can use, regardless of their abilities or disabilities. Accessible design is not just a nice-to-have—it''s a fundamental requirement for building inclusive products. Accessibility benefits everyone, not just people with disabilities.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key principles include: use sufficient color contrast, provide text alternatives for images, make interactive elements keyboard accessible, use clear and simple language, and test with assistive technologies. Accessibility is not an afterthought—it should be built into every aspect of your design process.","type":"text"}]},{"type":"paragraph","content":[{"text":"Accessible design is good design. When you design for accessibility, you create products that are more usable, more inclusive, and more successful. Accessibility is not a constraint—it''s an opportunity to build better products for everyone.","type":"text"}]}]}',
 'Why accessibility is essential in design and how to implement it.',
 '["Design"]', 5, 620, 'published', NOW() - interval '3 days', 80, 11, 2, false, 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800&q=80', NOW(), NOW()),

-- Data Science posts (3)
('20000000-0000-0000-0000-000000000025', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'data-science-fundamentals', 'Data Science Fundamentals',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Data science is the field of extracting knowledge and insights from data. It combines statistics, programming, and domain expertise to solve complex problems and make data-driven decisions. Data science is transforming industries from healthcare to finance to entertainment.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key skills include: data cleaning and preparation, exploratory data analysis, statistical modeling, machine learning, and data visualization. Data scientists use tools like Python, R, SQL, and various libraries and frameworks to work with data.","type":"text"}]},{"type":"paragraph","content":[{"text":"Data science is not just about analyzing data—it''s about asking the right questions, finding meaningful patterns, and communicating insights effectively. The best data scientists are curious, analytical, and good communicators.","type":"text"}]}]}',
 'An introduction to data science and its key concepts and skills.',
 '["Data Science"]', 5, 600, 'published', NOW() - interval '1 day', 70, 10, 2, false, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000026', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'data-visualization-best-practices', 'Data Visualization Best Practices',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Data visualization is the art and science of presenting data in a way that is clear, accurate, and compelling. Good data visualization helps people understand complex information quickly and make better decisions. Poor visualization can mislead, confuse, or bore your audience.","type":"text"}]},{"type":"paragraph","content":[{"text":"Best practices include: choose the right chart type for your data, use color purposefully, keep it simple, provide context, and tell a story with your data. The goal is to communicate insights, not just display numbers.","type":"text"}]},{"type":"paragraph","content":[{"text":"Data visualization is a powerful tool for communication. When done well, it can reveal patterns, highlight trends, and make complex data accessible to everyone. When done poorly, it can obscure the truth and mislead your audience.","type":"text"}]}]}',
 'Best practices for creating clear and compelling data visualizations.',
 '["Data Science"]', 5, 580, 'published', NOW() - interval '2 days', 60, 9, 2, false, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000027', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'big-data-analytics', 'Big Data Analytics: An Introduction',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Big data refers to datasets that are too large or complex for traditional data processing tools. Big data analytics is the process of examining these large datasets to uncover patterns, trends, and insights. It''s transforming how organizations make decisions and understand their customers.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key technologies include: distributed computing (Hadoop, Spark), data storage (HDFS, NoSQL databases), data processing (MapReduce, SQL), and machine learning. Big data analytics requires specialized tools and techniques to handle the volume, velocity, and variety of modern data.","type":"text"}]},{"type":"paragraph","content":[{"text":"Big data analytics is not just about technology—it''s about using data to solve real problems and create value. The most successful organizations are those that can turn big data into actionable insights.","type":"text"}]}]}',
 'An introduction to big data analytics and its applications.',
 '["Data Science"]', 5, 560, 'published', NOW() - interval '3 days', 50, 8, 2, false, 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&q=80', NOW(), NOW()),

-- Cybersecurity posts (3)
('20000000-0000-0000-0000-000000000028', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'zero-trust-security', 'Zero Trust Security: A Modern Approach',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Zero trust is a security model that assumes no user or device is trustworthy by default, even if they''re inside the network perimeter. Instead of trusting everything inside the network, zero trust requires verification for every access request, regardless of where it comes from. This approach provides better security in today''s distributed and cloud-based world.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key principles include: verify explicitly (always authenticate and authorize), use least privilege access (limit access to what''s needed), and assume breach (plan for the worst). Zero trust requires continuous monitoring, micro-segmentation, and strong identity and access management.","type":"text"}]},{"type":"paragraph","content":[{"text":"Zero trust is not a product you can buy—it''s a security philosophy and architecture. Implementing zero trust requires a fundamental shift in how you think about security, but it provides much better protection in today''s threat landscape.","type":"text"}]}]}',
 'Understanding zero trust security and how to implement it.',
 '["Cybersecurity"]', 5, 540, 'published', NOW() - interval '1 day', 40, 7, 2, false, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000029', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'ransomware-protection', 'Ransomware Protection: How to Defend Your Organization',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Ransomware is one of the most damaging cyber threats facing organizations today. It encrypts your data and demands payment for its release. Ransomware attacks can cripple businesses, hospitals, and governments, causing millions in damages and lost productivity.","type":"text"}]},{"type":"paragraph","content":[{"text":"Protection strategies include: regular backups (offline and tested), employee training (recognize phishing attempts), endpoint protection (antivirus and EDR), network segmentation (limit lateral movement), and incident response planning (know what to do when attacked). Prevention is always better than recovery.","type":"text"}]},{"type":"paragraph","content":[{"text":"Ransomware is a serious threat, but it''s not inevitable. With the right defenses, training, and preparation, you can significantly reduce your risk and minimize the impact of an attack.","type":"text"}]}]}',
 'How to protect your organization from ransomware attacks.',
 '["Cybersecurity"]', 5, 520, 'published', NOW() - interval '2 days', 35, 6, 2, false, 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80', NOW(), NOW()),

('20000000-0000-0000-0000-000000000030', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'security-awareness-training', 'Security Awareness Training for Employees',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Employees are often the weakest link in cybersecurity. Phishing, social engineering, and human error are responsible for many security breaches. Security awareness training is essential for teaching employees how to recognize and respond to security threats.","type":"text"}]},{"type":"paragraph","content":[{"text":"Effective training includes: recognizing phishing emails, using strong passwords, enabling two-factor authentication, being cautious with links and attachments, and knowing how to report security incidents. Training should be regular, engaging, and relevant to employees'' daily work.","type":"text"}]},{"type":"paragraph","content":[{"text":"Security awareness is not a one-time event—it''s an ongoing process. Regular training, simulated phishing tests, and a culture of security awareness can significantly reduce your organization''s risk.","type":"text"}]}]}',
 'The importance of security awareness training for employees.',
 '["Cybersecurity"]', 5, 500, 'published', NOW() - interval '3 days', 30, 5, 2, false, 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
