-- Add more tech-focused posts like Medium
-- Topics: AI, Software Engineering, Developer Tools, Tech Culture, Open Source, DevOps, Mobile Development, Blockchain, Game Development, Tech News

INSERT INTO posts (id, author_id, slug, title, content, excerpt, tags, reading_time_minutes, word_count, status, published_at, view_count, like_count, comment_count, is_premium, cover_image_url, created_at, updated_at) VALUES

-- AI posts (5)
('30000000-0000-0000-0000-000000000001', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'ai-agents-autonomous-systems', 'AI Agents: The Future of Autonomous Systems',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"AI agents are autonomous systems that can perceive their environment, make decisions, and take actions to achieve goals. Unlike simple automation, AI agents can adapt, learn, and operate with minimal human intervention. They''re transforming how we think about software and automation.","type":"text"}]},{"type":"paragraph","content":[{"text":"Modern AI agents use large language models, reinforcement learning, and tool use to accomplish complex tasks. They can browse the web, write code, analyze data, and even interact with other agents. The potential applications are vast: from customer service to research to creative work.","type":"text"}]},{"type":"paragraph","content":[{"text":"As AI agents become more capable, the challenge will be ensuring they act responsibly and align with human values. The future of AI is not just about intelligence—it''s about autonomy, responsibility, and collaboration.","type":"text"}]}]}',
 'How AI agents are transforming automation and autonomous systems.',
 '["AI"]', 5, 1000, 'published', NOW() - interval '6 days', 290, 47, 6, false, 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000002', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'prompt-engineering-guide', 'Prompt Engineering: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Prompt engineering is the art and science of crafting inputs to get the best outputs from AI models. It''s a new skill that''s becoming essential as AI becomes more integrated into our work. Good prompts can dramatically improve the quality, accuracy, and usefulness of AI responses.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key techniques include: being specific and clear, providing context and examples, using step-by-step reasoning, and iterating on prompts. The best prompts are clear, concise, and provide the model with the information it needs to give you the best answer.","type":"text"}]},{"type":"paragraph","content":[{"text":"Prompt engineering is not just about getting better answers—it''s about understanding how AI models work and how to communicate with them effectively. It''s a skill that will become increasingly valuable as AI becomes more prevalent.","type":"text"}]}]}',
 'How to craft effective prompts for AI models.',
 '["AI"]', 5, 950, 'published', NOW() - interval '7 days', 310, 53, 7, false, 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000003', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'ai-in-healthcare', 'AI in Healthcare: Transforming Medicine',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"AI is transforming healthcare in profound ways. From diagnosing diseases to personalizing treatment to accelerating drug discovery, AI is helping doctors provide better care and save lives. The potential for AI in healthcare is enormous.","type":"text"}]},{"type":"paragraph","content":[{"text":"Applications include: medical imaging analysis (detecting tumors and abnormalities), predictive analytics (identifying patients at risk), drug discovery (accelerating the development of new treatments), and personalized medicine (tailoring treatments to individual patients). AI is making healthcare more accurate, efficient, and accessible.","type":"text"}]},{"type":"paragraph","content":[{"text":"The future of healthcare is AI-augmented. AI will help doctors make better decisions, provide more personalized care, and improve outcomes for patients. The challenge will be ensuring AI is used responsibly and ethically in healthcare.","type":"text"}]}]}',
 'How AI is transforming healthcare and medicine.',
 '["AI"]', 5, 1020, 'published', NOW() - interval '8 days', 280, 44, 5, false, 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000004', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'ai-in-education', 'AI in Education: Personalized Learning',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"AI is transforming education by enabling personalized learning experiences. Instead of one-size-fits-all education, AI can adapt to each student''s pace, style, and needs. This has the potential to make education more effective, accessible, and engaging.","type":"text"}]},{"type":"paragraph","content":[{"text":"Applications include: adaptive learning platforms (adjusting content to student needs), intelligent tutoring systems (providing personalized guidance), automated grading (saving teachers time), and learning analytics (identifying students who need help). AI is making education more personalized and effective.","type":"text"}]},{"type":"paragraph","content":[{"text":"The future of education is AI-augmented. AI will help teachers provide better instruction, students learn more effectively, and schools operate more efficiently. The challenge will be ensuring AI enhances, rather than replaces, the human elements of education.","type":"text"}]}]}',
 'How AI is transforming education and personalized learning.',
 '["AI"]', 5, 980, 'published', NOW() - interval '9 days', 260, 41, 4, false, 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000005', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'ai-and-creativity', 'AI and Creativity: The Future of Art and Design',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"AI is transforming creativity in art, design, music, and writing. AI tools can generate images, compose music, write stories, and create designs. This is changing how we think about creativity and the role of human artists.","type":"text"}]},{"type":"paragraph","content":[{"text":"AI can be a powerful tool for creativity: it can generate ideas, provide inspiration, and help artists work faster. But it also raises questions about originality, copyright, and the value of human creativity. The future of art will likely be a collaboration between human creativity and AI tools.","type":"text"}]},{"type":"paragraph","content":[{"text":"The future of creativity is not AI replacing artists—it''s AI empowering artists. AI will help artists explore new ideas, work faster, and create things that were previously impossible. The most successful artists will be those who can harness AI as a tool for their creativity.","type":"text"}]}]}',
 'How AI is transforming creativity in art and design.',
 '["AI"]', 5, 960, 'published', NOW() - interval '10 days', 240, 38, 5, false, 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80', NOW(), NOW()),

-- Software Engineering posts (5)
('30000000-0000-0000-0000-000000000006', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'microservices-architecture', 'Microservices Architecture: Pros and Cons',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Microservices architecture is an approach to building applications as a collection of small, independent services that communicate over a network. Each service is responsible for a specific business capability and can be developed, deployed, and scaled independently. This approach has become popular for building large, complex applications.","type":"text"}]},{"type":"paragraph","content":[{"text":"Benefits include: independent deployment, technology diversity, scalability, and team autonomy. Drawbacks include: increased complexity, distributed system challenges, data consistency issues, and operational overhead. Microservices are not a silver bullet—they''re a tool that''s appropriate for some problems and not others.","type":"text"}]},{"type":"paragraph","content":[{"text":"Microservices are powerful for large, complex applications with multiple teams, but they''re overkill for small applications. The key is understanding when microservices make sense and when a simpler architecture is better.","type":"text"}]}]}',
 'Understanding microservices architecture and when to use it.',
 '["Software Engineering"]', 5, 940, 'published', NOW() - interval '6 days', 250, 39, 5, false, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000007', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'domain-driven-design', 'Domain-Driven Design: Building Better Software',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Domain-Driven Design (DDD) is an approach to software development that focuses on understanding and modeling the business domain. DDD helps you build software that accurately reflects the business logic and requirements. It''s about understanding the problem before solving it.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key concepts include: ubiquitous language (a shared vocabulary between developers and domain experts), bounded contexts (clear boundaries between different parts of the system), and domain models (rich, behavior-driven models). DDD helps you build software that is more maintainable, understandable, and aligned with business needs.","type":"text"}]},{"type":"paragraph","content":[{"text":"DDD is not a silver bullet, but it''s a powerful approach for complex business applications. It helps you build software that accurately reflects the business domain and is easier to maintain and evolve.","type":"text"}]}]}',
 'Understanding Domain-Driven Design and how to apply it.',
 '["Software Engineering"]', 5, 920, 'published', NOW() - interval '7 days', 230, 36, 4, false, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000008', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'refactoring-legacy-code', 'Refactoring Legacy Code: A Practical Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Legacy code is code that''s hard to understand, maintain, and modify. It''s often poorly documented, lacks tests, and has grown organically over time. Refactoring legacy code is one of the most challenging and important tasks in software development.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key strategies include: write tests first (to ensure you don''t break anything), refactor in small steps (don''t try to do everything at once), improve incrementally (make it better, not perfect), and document as you go (help future developers). The goal is to make the code more maintainable without breaking functionality.","type":"text"}]},{"type":"paragraph","content":[{"text":"Refactoring legacy code is not glamorous, but it''s essential for maintaining a healthy codebase. Done well, it can transform a tangled mess into clean, maintainable code. Done poorly, it can introduce bugs and break functionality.","type":"text"}]}]}',
 'How to refactor legacy code safely and effectively.',
 '["Software Engineering"]', 5, 900, 'published', NOW() - interval '8 days', 210, 33, 4, false, 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000009', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'code-review-best-practices', 'Code Review Best Practices',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Code review is one of the most important practices in software development. It helps catch bugs, share knowledge, improve code quality, and build better teams. But not all code reviews are created equal. Good code reviews are collaborative, constructive, and focused on learning.","type":"text"}]},{"type":"paragraph","content":[{"text":"Best practices include: keep reviews small and focused, be respectful and constructive, focus on the code not the person, ask questions rather than make demands, and automate what you can (linters, formatters, tests). The goal is to improve the code and help the author learn.","type":"text"}]},{"type":"paragraph","content":[{"text":"Code review is not just about finding bugs—it''s about building better software and better teams. When done well, code review improves code quality, shares knowledge, and strengthens team culture.","type":"text"}]}]}',
 'How to conduct effective code reviews.',
 '["Software Engineering"]', 5, 880, 'published', NOW() - interval '9 days', 190, 30, 4, false, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000010', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'software-documentation-guide', 'Software Documentation: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Good documentation is essential for maintainable software. It helps developers understand the code, onboard new team members, and maintain the system over time. But writing good documentation is hard—it requires clarity, accuracy, and keeping it up to date.","type":"text"}]},{"type":"paragraph","content":[{"text":"Types of documentation include: README files (project overview), API documentation (how to use the API), code comments (explaining complex logic), and architecture documentation (high-level design). Each type serves a different purpose and audience.","type":"text"}]},{"type":"paragraph","content":[{"text":"Good documentation is not just about writing—it''s about communication. It should be clear, accurate, and helpful. The best documentation is the kind that developers actually read and use.","type":"text"}]}]}',
 'How to write effective software documentation.',
 '["Software Engineering"]', 5, 860, 'published', NOW() - interval '10 days', 170, 27, 3, false, 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&q=80', NOW(), NOW()),

-- Developer Tools posts (5)
('30000000-0000-0000-0000-000000000011', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'developer-productivity-tools', 'Developer Productivity Tools You Should Know',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Developer productivity tools can dramatically improve your workflow and efficiency. From IDEs to terminal tools to automation scripts, the right tools can save you hours every week. The best developers are not just skilled—they''re also efficient with their tools.","type":"text"}]},{"type":"paragraph","content":[{"text":"Essential tools include: a good IDE (VS Code, IntelliJ), terminal tools (tmux, zsh, fzf), version control (Git), package managers, and automation scripts. These tools help you write code faster, debug more efficiently, and automate repetitive tasks.","type":"text"}]},{"type":"paragraph","content":[{"text":"The right tools can make you a more productive and effective developer. Invest time in learning and customizing your tools—it''s one of the best investments you can make in your development career.","type":"text"}]}]}',
 'Essential tools for developer productivity.',
 '["Developer Tools"]', 5, 840, 'published', NOW() - interval '6 days', 180, 28, 4, false, 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000012', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'vscode-extensions-guide', 'VS Code Extensions Every Developer Should Use',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"VS Code is one of the most popular code editors, and for good reason: it''s fast, extensible, and free. But what makes VS Code truly powerful is its extensions. The right extensions can transform VS Code from a simple editor into a powerful development environment.","type":"text"}]},{"type":"paragraph","content":[{"text":"Essential extensions include: language support (Python, JavaScript, Go), debugging tools, Git integration, code formatters (Prettier), linters (ESLint), and productivity tools (Live Share, Remote Development). These extensions help you write, debug, and collaborate on code more effectively.","type":"text"}]},{"type":"paragraph","content":[{"text":"The right extensions can make VS Code work exactly how you want it to. Take time to explore and customize your setup—it''s one of the best ways to improve your development workflow.","type":"text"}]}]}',
 'Essential VS Code extensions for developers.',
 '["Developer Tools"]', 5, 820, 'published', NOW() - interval '7 days', 160, 25, 3, false, 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000013', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'terminal-productivity', 'Terminal Productivity: Mastering the Command Line',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"The command line is one of the most powerful tools in a developer''s toolkit. Mastering the terminal can dramatically improve your productivity and efficiency. From navigating the filesystem to automating tasks to managing servers, the command line is essential for modern development.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key skills include: navigating the filesystem, using pipes and redirects, writing shell scripts, using terminal multiplexers (tmux), and customizing your shell (zsh, oh-my-zsh). These skills help you work faster and more efficiently.","type":"text"}]},{"type":"paragraph","content":[{"text":"The command line is not just a tool—it''s a superpower. Mastering it can make you a more productive and effective developer. Invest time in learning and customizing your terminal setup.","type":"text"}]}]}',
 'How to master the command line for developer productivity.',
 '["Developer Tools"]', 5, 800, 'published', NOW() - interval '8 days', 150, 23, 3, false, 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000014', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'git-workflows-explained', 'Git Workflows Explained',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Git workflows are strategies for using Git to collaborate on code. Different workflows have different strengths and are appropriate for different teams and projects. Understanding Git workflows is essential for effective collaboration in software development.","type":"text"}]},{"type":"paragraph","content":[{"text":"Common workflows include: Git Flow (feature branches, develop, main), GitHub Flow (simple feature branches), and Trunk-Based Development (work directly on main). Each workflow has its own strengths and tradeoffs. The best workflow depends on your team''s size, experience, and release cadence.","type":"text"}]},{"type":"paragraph","content":[{"text":"The right Git workflow can make your team more productive and your codebase more stable. Choose a workflow that fits your team''s needs and stick to it consistently.","type":"text"}]}]}',
 'Understanding different Git workflows and when to use them.',
 '["Developer Tools"]', 5, 780, 'published', NOW() - interval '9 days', 140, 21, 3, false, 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000015', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'debugging-techniques', 'Debugging Techniques Every Developer Should Know',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Debugging is one of the most important skills in software development. Bugs are inevitable, but good debugging techniques can help you find and fix them quickly. Effective debugging is not just about finding bugs—it''s about understanding your code and improving it.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key techniques include: using a debugger (breakpoints, step-through), adding logging and print statements, rubber duck debugging (explaining the problem out loud), and writing tests to reproduce bugs. The best debugging is systematic and methodical.","type":"text"}]},{"type":"paragraph","content":[{"text":"Debugging is not just about fixing bugs—it''s about understanding your code and making it better. Good debugging skills can save you hours of frustration and help you write better code.","type":"text"}]}]}',
 'Essential debugging techniques for developers.',
 '["Developer Tools"]', 5, 760, 'published', NOW() - interval '10 days', 130, 20, 3, false, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', NOW(), NOW()),

-- Tech Culture posts (5)
('30000000-0000-0000-0000-000000000016', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'imposter-syndrome-tech', 'Imposter Syndrome in Tech: You''re Not Alone',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Imposter syndrome is the feeling that you''re not good enough, that you don''t belong, that you''ll be found out as a fraud. It''s incredibly common in tech, where the pace of change is fast and the pressure to know everything is high. But here''s the truth: everyone feels this way sometimes.","type":"text"}]},{"type":"paragraph","content":[{"text":"Imposter syndrome is not a sign of weakness—it''s a sign that you care about your work and want to do well. The most successful people in tech have felt imposter syndrome at some point. The key is recognizing it, understanding it, and not letting it hold you back.","type":"text"}]},{"type":"paragraph","content":[{"text":"You belong in tech. Your skills, experience, and perspective are valuable. Don''t let imposter syndrome stop you from pursuing your goals and sharing your work with the world.","type":"text"}]}]}',
 'Understanding and overcoming imposter syndrome in tech.',
 '["Tech Culture"]', 5, 740, 'published', NOW() - interval '6 days', 220, 35, 5, false, 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000017', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'burnout-in-tech', 'Burnout in Tech: How to Recognize and Prevent It',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Burnout is a state of physical, emotional, and mental exhaustion caused by prolonged stress. In tech, where the pace is fast and the pressure is high, burnout is increasingly common. Recognizing and preventing burnout is essential for a sustainable career in tech.","type":"text"}]},{"type":"paragraph","content":[{"text":"Signs of burnout include: exhaustion, cynicism, reduced productivity, and feeling overwhelmed. Prevention strategies include: setting boundaries, taking breaks, prioritizing self-care, and seeking support. Burnout is not a personal failure—it''s a systemic issue that requires systemic solutions.","type":"text"}]},{"type":"paragraph","content":[{"text":"Your health and wellbeing are more important than any job or project. If you''re feeling burned out, it''s okay to take a step back and prioritize your wellbeing. A sustainable career is a marathon, not a sprint.","type":"text"}]}]}',
 'How to recognize and prevent burnout in tech.',
 '["Tech Culture"]', 5, 720, 'published', NOW() - interval '7 days', 200, 32, 4, false, 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000018', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'diversity-in-tech', 'Diversity in Tech: Why It Matters',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Diversity in tech is not just a moral imperative—it''s a business imperative. Diverse teams are more innovative, more creative, and better at solving complex problems. But tech has a long way to go in terms of diversity and inclusion.","type":"text"}]},{"type":"paragraph","content":[{"text":"Diversity includes: gender diversity, racial and ethnic diversity, neurodiversity, and diversity of background and experience. Each type of diversity brings unique perspectives and strengths. The most innovative solutions come from diverse teams working together.","type":"text"}]},{"type":"paragraph","content":[{"text":"Building a more diverse and inclusive tech industry requires intentional effort: inclusive hiring practices, mentorship programs, and creating cultures where everyone feels welcome and valued. Diversity is not just about numbers—it''s about creating environments where everyone can thrive.","type":"text"}]}]}',
 'Why diversity in tech matters and how to build more inclusive teams.',
 '["Tech Culture"]', 5, 700, 'published', NOW() - interval '8 days', 180, 28, 4, false, 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000019', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'mentorship-in-tech', 'Mentorship in Tech: The Power of Guidance',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Mentorship is one of the most powerful tools for career growth in tech. A good mentor can help you navigate challenges, learn new skills, and advance your career. But finding and being a good mentor requires intentionality and effort.","type":"text"}]},{"type":"paragraph","content":[{"text":"Good mentorship includes: setting clear expectations, being available and supportive, sharing knowledge and experience, and providing honest feedback. The best mentorships are mutual—both the mentor and mentee learn and grow.","type":"text"}]},{"type":"paragraph","content":[{"text":"Mentorship is not just about career advancement—it''s about building relationships, sharing knowledge, and helping others succeed. Whether you''re a mentor or a mentee, mentorship can be one of the most rewarding aspects of a tech career.","type":"text"}]}]}',
 'The power of mentorship in tech careers.',
 '["Tech Culture"]', 5, 680, 'published', NOW() - interval '9 days', 160, 25, 3, false, 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000020', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'tech-interviews-guide', 'Tech Interviews: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Tech interviews can be intimidating, but they don''t have to be. With the right preparation and mindset, you can ace your tech interviews and land your dream job. The key is understanding what interviewers are looking for and how to demonstrate your skills effectively.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key strategies include: practice coding problems, prepare for behavioral questions, research the company, and be yourself. Tech interviews are not just about technical skills—they''re also about communication, problem-solving, and cultural fit.","type":"text"}]},{"type":"paragraph","content":[{"text":"Tech interviews are a two-way street. You''re also evaluating the company to see if it''s a good fit for you. Ask questions, be curious, and trust your instincts. The right job is out there for you.","type":"text"}]}]}',
 'How to prepare for and ace tech interviews.',
 '["Tech Culture"]', 5, 660, 'published', NOW() - interval '10 days', 140, 22, 3, false, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80', NOW(), NOW()),

-- Open Source posts (3)
('30000000-0000-0000-0000-000000000021', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'open-source-contribution-guide', 'Open Source Contribution: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Open source is one of the most powerful forces in software development. Contributing to open source projects is a great way to learn, build your portfolio, and give back to the community. But getting started with open source can be intimidating.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key steps include: find a project you care about, start small (documentation, bug fixes), read the contribution guidelines, and be patient and persistent. Open source is about collaboration and community, not just code.","type":"text"}]},{"type":"paragraph","content":[{"text":"Contributing to open source is not just about writing code—it''s about being part of a community. It''s about learning, sharing, and building something together. Whether you''re a beginner or an expert, there''s a place for you in open source.","type":"text"}]}]}',
 'How to contribute to open source projects.',
 '["Open Source"]', 5, 640, 'published', NOW() - interval '6 days', 120, 19, 3, false, 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000022', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'open-source-licenses-explained', 'Open Source Licenses Explained',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Open source licenses are legal agreements that govern how open source software can be used, modified, and distributed. Understanding open source licenses is essential for anyone using or contributing to open source software. But with so many licenses, it can be confusing.","type":"text"}]},{"type":"paragraph","content":[{"text":"Common licenses include: MIT (permissive, allows almost anything), Apache 2.0 (permissive with patent grant), GPL (copyleft, requires sharing modifications), and BSD (permissive). Each license has different requirements and restrictions. Choosing the right license depends on your goals and values.","type":"text"}]},{"type":"paragraph","content":[{"text":"Open source licenses are not just legal documents—they''s about community and collaboration. They enable sharing and collaboration while protecting the rights of creators and users. Understanding licenses helps you use and contribute to open source responsibly.","type":"text"}]}]}',
 'Understanding different open source licenses and how to choose them.',
 '["Open Source"]', 5, 620, 'published', NOW() - interval '7 days', 100, 16, 2, false, 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000023', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'building-open-source-community', 'Building an Open Source Community',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Building an open source community is about more than just code—it''s about people, collaboration, and shared goals. A strong open source community can make your project more successful, more sustainable, and more impactful.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key elements include: clear documentation, welcoming community, responsive maintainers, and good governance. Building a community takes time and effort, but it''s essential for the long-term success of your project.","type":"text"}]},{"type":"paragraph","content":[{"text":"Open source is not just about the code—it''s about the people. Building a strong community around your project can make it more successful, more sustainable, and more rewarding for everyone involved.","type":"text"}]}]}',
 'How to build and grow an open source community.',
 '["Open Source"]', 5, 600, 'published', NOW() - interval '8 days', 90, 14, 2, false, 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80', NOW(), NOW()),

-- DevOps posts (3)
('30000000-0000-0000-0000-000000000024', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'devops-fundamentals', 'DevOps Fundamentals: Bridging Development and Operations',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). It''s about breaking down silos between teams and working together to deliver software faster, more reliably, and more efficiently. DevOps is not just about tools—it''s about culture, collaboration, and continuous improvement.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key practices include: continuous integration and continuous deployment (CI/CD), infrastructure as code, monitoring and logging, and automation. DevOps helps teams deliver software faster, with fewer errors, and with better quality.","type":"text"}]},{"type":"paragraph","content":[{"text":"DevOps is not just a set of tools—it''s a way of working. It''s about collaboration, automation, and continuous improvement. Adopting DevOps practices can transform how your team builds and delivers software.","type":"text"}]}]}',
 'Understanding DevOps and how to implement it.',
 '["DevOps"]', 5, 580, 'published', NOW() - interval '6 days', 80, 13, 2, false, 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000025', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'ci-cd-pipelines-guide', 'CI/CD Pipelines: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"CI/CD (Continuous Integration and Continuous Deployment) is a set of practices that automate the building, testing, and deployment of software. CI/CD pipelines help teams deliver software faster, more reliably, and with fewer errors. They''re essential for modern software development.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key components include: automated builds, automated testing, automated deployment, and monitoring. A good CI/CD pipeline catches errors early, deploys quickly, and provides feedback to developers. CI/CD is not just about automation—it''s about quality and speed.","type":"text"}]},{"type":"paragraph","content":[{"text":"CI/CD is not just about tools—it''s about process and culture. A good CI/CD pipeline helps teams deliver software faster, with fewer errors, and with better quality. Implementing CI/CD can transform how your team builds and delivers software.","type":"text"}]}]}',
 'How to build and use CI/CD pipelines for software delivery.',
 '["DevOps"]', 5, 560, 'published', NOW() - interval '7 days', 70, 11, 2, false, 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000026', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'infrastructure-as-code', 'Infrastructure as Code: Managing Infrastructure with Code',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Infrastructure as Code (IaC) is the practice of managing and provisioning infrastructure through code instead of manual processes. IaC enables you to automate infrastructure deployment, make it repeatable, and manage it like software. It''s essential for modern DevOps practices.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key tools include: Terraform (multi-cloud), CloudFormation (AWS), Ansible (configuration management), and Pulumi (modern IaC). IaC helps you manage infrastructure consistently, reliably, and at scale.","type":"text"}]},{"type":"paragraph","content":[{"text":"IaC is not just about automation—it''s about treating infrastructure like software. It enables version control, testing, and collaboration for infrastructure. Adopting IaC can transform how you manage and deploy infrastructure.","type":"text"}]}]}',
 'How to manage infrastructure with Infrastructure as Code.',
 '["DevOps"]', 5, 540, 'published', NOW() - interval '8 days', 60, 10, 2, false, 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&q=80', NOW(), NOW()),

-- Mobile Development posts (3)
('30000000-0000-0000-0000-000000000027', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'mobile-development-trends', 'Mobile Development Trends for 2026',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Mobile development is evolving rapidly. New frameworks, tools, and paradigms are changing how we build mobile applications. From cross-platform development to AI integration to progressive web apps, the future of mobile development is exciting and dynamic.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key trends include: cross-platform development (React Native, Flutter), AI integration (on-device ML, cloud AI), progressive web apps (web apps that feel native), and 5G integration (faster, more reliable connectivity). These trends are changing how we build and use mobile apps.","type":"text"}]},{"type":"paragraph","content":[{"text":"The future of mobile development is about building better experiences for users and developers alike. As tools improve and best practices evolve, mobile development will continue to be a dynamic and exciting field.","type":"text"}]}]}',
 'Current trends in mobile development.',
 '["Mobile Development"]', 5, 520, 'published', NOW() - interval '6 days', 50, 9, 2, false, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000028', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'react-native-vs-flutter', 'React Native vs Flutter: Which Should You Choose?',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"React Native and Flutter are the two most popular frameworks for cross-platform mobile development. Both allow you to build mobile apps for iOS and Android from a single codebase. But they have different strengths, weaknesses, and use cases. Choosing between them depends on your project, team, and goals.","type":"text"}]},{"type":"paragraph","content":[{"text":"React Native uses JavaScript and React, making it easy for web developers to transition to mobile. Flutter uses Dart and provides a more native feel and better performance. React Native has a larger ecosystem and more third-party libraries. Flutter has better performance and a more consistent UI.","type":"text"}]},{"type":"paragraph","content":[{"text":"The best choice depends on your project, team, and goals. Both are excellent frameworks that can help you build high-quality mobile apps quickly and efficiently.","type":"text"}]}]}',
 'Comparing React Native and Flutter for mobile development.',
 '["Mobile Development"]', 5, 500, 'published', NOW() - interval '7 days', 45, 8, 2, false, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000029', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'mobile-app-security', 'Mobile App Security: Best Practices',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Mobile app security is critical for protecting user data and maintaining trust. Mobile apps handle sensitive information, and security breaches can have serious consequences. Following security best practices is essential for building safe and trustworthy mobile apps.","type":"text"}]},{"type":"paragraph","content":[{"text":"Best practices include: encrypting data at rest and in transit, using secure authentication, implementing proper session management, validating inputs, and keeping dependencies updated. Mobile security is not just about technology—it''s about building secure apps from the ground up.","type":"text"}]},{"type":"paragraph","content":[{"text":"Mobile app security is not optional—it''s essential. By following security best practices, you can build mobile apps that are safe, secure, and trustworthy.","type":"text"}]}]}',
 'Best practices for mobile app security.',
 '["Mobile Development"]', 5, 480, 'published', NOW() - interval '8 days', 40, 7, 2, false, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80', NOW(), NOW()),

-- Blockchain posts (3)
('30000000-0000-0000-0000-000000000030', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'blockchain-beyond-cryptocurrency', 'Blockchain Beyond Cryptocurrency: Real-World Applications',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Blockchain is often associated with cryptocurrency, but its applications go far beyond digital money. Blockchain is a distributed ledger technology that can be used for supply chain tracking, digital identity, smart contracts, and more. Understanding blockchain''s potential beyond cryptocurrency is essential for seeing its real value.","type":"text"}]},{"type":"paragraph","content":[{"text":"Applications include: supply chain tracking (verifying product authenticity), digital identity (secure, decentralized identity), smart contracts (self-executing contracts), and decentralized finance (DeFi). Blockchain can provide transparency, security, and trust in many applications.","type":"text"}]},{"type":"paragraph","content":[{"text":"Blockchain is not just about cryptocurrency—it''s about creating more transparent, secure, and decentralized systems. Understanding blockchain''s potential can help you see where it can add value in your applications.","type":"text"}]}]}',
 'Real-world applications of blockchain beyond cryptocurrency.',
 '["Blockchain"]', 5, 460, 'published', NOW() - interval '6 days', 35, 6, 2, false, 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000031', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'smart-contracts-explained', 'Smart Contracts Explained',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Smart contracts are self-executing contracts with the terms of the agreement written directly into code. They run on blockchain networks and automatically execute when predefined conditions are met. Smart contracts enable trustless, automated agreements without intermediaries.","type":"text"}]},{"type":"paragraph","content":[{"text":"Applications include: decentralized finance (DeFi), supply chain management, digital identity, and automated payments. Smart contracts can automate complex agreements, reduce costs, and increase transparency.","type":"text"}]},{"type":"paragraph","content":[{"text":"Smart contracts are not just about automation—they''s about creating more transparent, efficient, and trustworthy systems. Understanding smart contracts can help you see where they can add value in your applications.","type":"text"}]}]}',
 'Understanding smart contracts and how they work.',
 '["Blockchain"]', 5, 440, 'published', NOW() - interval '7 days', 30, 5, 2, false, 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000032', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'web3-development-guide', 'Web3 Development: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Web3 is the next generation of the internet, built on blockchain and decentralized technologies. Web3 enables decentralized applications (dApps), decentralized finance (DeFi), and user-owned data. Understanding Web3 development is essential for building the future of the internet.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key technologies include: blockchain networks (Ethereum, Solana), smart contracts (Solidity), decentralized storage (IPFS), and Web3 libraries (ethers.js, web3.js). Web3 development requires understanding both traditional web development and blockchain concepts.","type":"text"}]},{"type":"paragraph","content":[{"text":"Web3 is not just about technology—it''s about creating a more decentralized, user-owned internet. Understanding Web3 development can help you build the next generation of internet applications.","type":"text"}]}]}',
 'A complete guide to Web3 development.',
 '["Blockchain"]', 5, 420, 'published', NOW() - interval '8 days', 25, 4, 2, false, 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80', NOW(), NOW()),

-- Game Development posts (3)
('30000000-0000-0000-0000-000000000033', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'game-development-fundamentals', 'Game Development Fundamentals',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Game development is the process of creating video games. It combines programming, design, art, and storytelling to create interactive experiences. Game development is a challenging but rewarding field that requires creativity, technical skill, and passion.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key aspects include: game engines (Unity, Unreal), programming (C#, C++, GDScript), game design (mechanics, level design, storytelling), and art (2D/3D graphics, animation, sound). Game development requires a diverse set of skills and collaboration across disciplines.","type":"text"}]},{"type":"paragraph","content":[{"text":"Game development is not just about technology—it''s about creating experiences that engage and entertain players. The best games are those that combine technical excellence with creative vision.","type":"text"}]}]}',
 'An introduction to game development and its key aspects.',
 '["Game Development"]', 5, 400, 'published', NOW() - interval '6 days', 20, 3, 2, false, 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000034', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'game-design-principles', 'Game Design Principles for Engaging Games',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Game design is the art of creating engaging and fun games. Good game design is about creating experiences that are challenging, rewarding, and memorable. Understanding game design principles is essential for building games that players love.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key principles include: clear goals, meaningful choices, appropriate difficulty, feedback and rewards, and player agency. Good game design is about creating experiences that are engaging, challenging, and fun.","type":"text"}]},{"type":"paragraph","content":[{"text":"Game design is not just about making games—it''s about creating experiences that players remember and want to share. The best games are those that combine technical excellence with creative vision and player empathy.","type":"text"}]}]}',
 'Essential game design principles for creating engaging games.',
 '["Game Development"]', 5, 380, 'published', NOW() - interval '7 days', 15, 3, 2, false, 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80', NOW(), NOW()),

('30000000-0000-0000-0000-000000000035', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'indie-game-development', 'Indie Game Development: A Complete Guide',
 '{"type":"doc","content":[{"type":"paragraph","content":[{"text":"Indie game development is the process of creating games independently, without the backing of a large publisher. Indie games are often more creative, experimental, and personal than mainstream games. Indie game development offers creative freedom but also presents unique challenges.","type":"text"}]},{"type":"paragraph","content":[{"text":"Key aspects include: choosing the right tools (game engines, art tools), managing scope (keep it small and focused), marketing and distribution (Steam, itch.io, social media), and building a community. Indie game development requires creativity, persistence, and resourcefulness.","type":"text"}]},{"type":"paragraph","content":[{"text":"Indie game development is not easy, but it''s one of the most rewarding things you can do. It offers creative freedom, the chance to tell your own stories, and the opportunity to build something truly unique.","type":"text"}]}]}',
 'A complete guide to indie game development.',
 '["Game Development"]', 5, 360, 'published', NOW() - interval '8 days', 10, 2, 2, false, 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&q=80', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
